package edu.hm.cs.swe2.memberfees;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Test class to see if Spring Application loads.
 * 
 * @author Jonas Buse (autogenerated)
 */
@SpringBootTest
class ApplicationTests {

	@Test
	void contextLoads() {
	}

}
